FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml ./
RUN pip install uv
RUN uv pip install --system -r pyproject.toml

COPY . .

CMD ["celery", "-A", "app.workers.tasks", "worker", "--loglevel=info", "--pool=solo"]
